### ISSUE TITLE
Add android platform fails

### ISSUE THREAD

**Issue by Chirag-Chauhan** [Azure-Samples/active-directory-cordova-multitarget#2]
I am using following command to add the Android platform: cordova platform add android@97718a0a25ec50fedf7b023ae63bfcffbcfafb4b. But it fails with error "Unable to fetch platform android@97718a0a25ec50fedf7b023ae63bfcffbcfafb4b: Error: tunneling socket could not be established, cause=connect ECONNREFUSED".

On a side note, I am successfully able to add iOS platform.

Any help will be appreciated.

Thanks.

**Comment by jmprieur** [comment]
this sample is being archived
